### ISSUE TITLE
The last step of the tutorial about config.ts

### ISSUE THREAD

**Issue by Ashygoyal** [cosmicjs/ionic-angular-app#1]
Guys, no file like '**config.ts**' exists in the whole project. Can anyone suggest, where else to make that connection between Ionic app and Cosmic JS custom bucket?
(I followed the tutorial from: https://cosmicjs.com/blog/how-to-build-a-mobile-product-catalog-app-using-angular-js-ionic-and-cosmic-js)
```
export default {
  bucket: {
    slug: 'ionic-angular-app'
  }
}
```
I am getting the below error, on ionic serve

```
Error: Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_2_cosmicjs___default.a.getObjectType is not a function
TypeError: __WEBPACK_IMPORTED_MODULE_2_cosmicjs___default.a.getObjectType is not a function
    at new CategoriesList (http://localhost:8100/build/main.js:176:58)
    at createClass (http://localhost:8100/build/vendor.js:12855:20)
    at createDirectiveInstance (http://localhost:8100/build/vendor.js:12700:37)
    at createViewNodes (http://localhost:8100/build/vendor.js:14158:53)
    at createRootView (http://localhost:8100/build/vendor.js:14047:5)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15472:42)
    at Object.debugCreateRootView [as createRootView] (http://localhost:8100/build/vendor.js:14755:12)
    at ComponentFactory_.create (http://localhost:8100/build/vendor.js:11652:46)
    at ComponentFactoryBoundToModule.create (http://localhost:8100/build/vendor.js:4404:29)
    at Tab.NavControllerBase._viewInit (http://localhost:8100/build/vendor.js:52225:44)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at c (http://localhost:8100/build/polyfills.js:3:19461)
    at http://localhost:8100/build/polyfills.js:3:20233
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5125:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at o (http://localhost:8100/build/polyfills.js:3:7894)
```

Other details are as follows: 
```

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.9
Angular Core: 5.2.10
Angular Compiler CLI: 5.2.10
Node: 8.11.1
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
```
Any clues here?

Thanks in advance!

**Comment by Ashygoyal** [comment]
Resolved the first part of the above issue, by using the '**cosmic cli**' way to achieve the same. 
But the same TypeError still persists after executing `ionic serve`. 
Any suggestions @tonyspiro sir?
